apiVersion: v1
kind: Pod
metadata:
  name: plf-pod-bt-4000-shell-pod
  labels:
    app: plf-tester
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: plf-container
      image: mayabasu/plf_images:path3test
      resources:
        limits:
          memory: "5Gi"
        requests:
          memory: "4Gi"
      env:
        - name: lossFunctionId #mse:0 sl:1,bce:2,ae:3,isl:4
          value: "3"
        - name: numEpochs
          value: "3200"
        - name: learningRate
          value: "0.0001"
        - name: systematicError
          value: "0.5"
        - name: numTrainingBatches
          value: "50"
        - name: numTestingBatches
          value: "12"
        - name: trainBatchSize
          value: "4000"
        - name: testBatchSize
          value: "4000"
        - name: testNote
          value: "0.5_bt_shell-pod"
      volumeMounts:
      - mountPath: /app/task-pv-claim
        name: task-pv-storage
