apiVersion: v1
kind: Pod
metadata:
  name: plf-pod-10000
  labels:
    app: plf-tester
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: plf-container
      image: mayabasu/plf_images:test2
      env:
        - name: lossFunctionId #mse:0 sl:1,bce:2,ae:3,isl:4
          value: "3"
        - name: numEpochs
          value: "1600"
        - name: learningRate
          value: "0.001"
        - name: systematicError
          value: "0.5"
        - name: numTrainingBatches
          value: "20"
        - name: numTestingBatches
          value: "12"
        - name: trainBatchSize
          value: "10000"
        - name: testBatchSize
          value: "4000"
        - name: testNote
          value: "0.5_10000"
      volumeMounts:
      - mountPath: /app/task-pv-claim
        name: task-pv-storage
